# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "csv"
gem "bigdecimal"
gem "github-pages", "232", group: :jekyll_plugins
gem "concurrent-ruby", ">= 1.3.7"
gem "faraday", ">= 2.14.3"
gem "json", ">= 2.19.9"
gem "nokogiri", ">= 1.19.4"
