# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "csv"
gem "bigdecimal"
gem "jekyll", "~> 4.4"
gem "rubyzip", ">= 3.4.0", "< 4.0"

group :jekyll_plugins do
  gem "jekyll-default-layout", "~> 0.1.5"
  gem "jekyll-github-metadata", "~> 2.16.1"
  gem "jekyll-include-cache", "~> 0.2"
  gem "jekyll-optional-front-matter", "~> 0.3.2"
  gem "jekyll-relative-links", "~> 0.6.1"
  gem "jekyll-remote-theme", "~> 0.5.2"
  gem "jekyll-seo-tag", "~> 2.8"
end

gem "concurrent-ruby", ">= 1.3.7"
gem "faraday", ">= 2.14.3"
gem "json", ">= 2.19.9"
gem "nokogiri", ">= 1.19.4"
